server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: farmer-service
          uri: lb://farmer-service
          predicates:
            - Path=/api/farmers/**

        - id: runner-service
          uri: lb://runner-service
          predicates:
            - Path=/api/runners/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/api/locations/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/