server:
  port: 8089

spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://localhost:5432/farmdirect_media
    username: postgres
    password: sampath12222@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloudinary:
  cloud-name: du3vjsl6a
  api-key: 726778151121488
  api-secret: IXjX3aE0i6gmXCeMU114modYN3o


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
